version: "3.8"

services:
  postgresdb:
    image: postgres:14.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
  app:
    depends_on:
      - postgresdb
    image: begemot1987/university-tt
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DB?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "$POSTGRES_USER",
      "spring.datasource.password" : "$POSTGRES_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "create"
      }'
